const $=s=>document.querySelector(s);const accounts=JSON.parse(localStorage.getItem("phoneos-accounts")||"{}");let mode="login",current="";
function show(m){mode=m;document.querySelectorAll(".segmented button").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));$("#authText").textContent=m==="login"?"Continuar":"Crear cuenta";$("#emailLabel").classList.toggle("hidden",m==="login");$("#email").required=m==="register";$("#authMsg").textContent=""}
document.querySelectorAll(".segmented button").forEach(b=>b.onclick=()=>show(b.dataset.mode));
$("#authForm").onsubmit=e=>{e.preventDefault();const n=$("#username").value.trim(),email=$("#email").value.trim();if(!n)return;if(mode==="register"){accounts[n]={email,phoneName:n,accent:"#ffffff",bg:"#050505"};localStorage.setItem("phoneos-accounts",JSON.stringify(accounts));current=n;openPhone()}else{current=n;openPhone()}};
function openPhone(){const u=accounts[current]||{phoneName:current,accent:"#fff",bg:"#050505"};$("#authView").classList.add("hidden");$("#phoneView").classList.remove("hidden");$("#hello").textContent=u.phoneName;$("#phoneName").value=u.phoneName;$("#accent").value=u.accent||"#ffffff";setBg(u.bg||"#050505");applyAccent(u.accent||"#ffffff")}
function applyAccent(c){$("#phone").style.borderColor=c+"66";document.documentElement.style.setProperty("--accent",c)}
function setBg(c){$("#phone").style.background=c;document.querySelectorAll(".swatches button").forEach(b=>b.style.outline=b.dataset.bg===c?"2px solid #fff":"none")}
document.querySelectorAll(".swatches button").forEach(b=>b.onclick=()=>setBg(b.dataset.bg));$("#accent").oninput=e=>applyAccent(e.target.value);
$("#save").onclick=()=>{const u=accounts[current]||{};u.phoneName=$("#phoneName").value.trim()||current;u.accent=$("#accent").value;u.bg=$("#phone").style.background;accounts[current]=u;localStorage.setItem("phoneos-accounts",JSON.stringify(accounts));$("#hello").textContent=u.phoneName;$("#saveMsg").textContent="Personalización guardada ✓";setTimeout(()=>$("#saveMsg").textContent="",1800)};
$("#logout").onclick=()=>{$("#phoneView").classList.add("hidden");$("#authView").classList.remove("hidden");$("#authForm").reset();show("login")};
function clock(){const d=new Date(),t=d.toLocaleTimeString("es-PR",{hour:"2-digit",minute:"2-digit"});$("#time").textContent=t;$("#bigTime").textContent=t;$("#date").textContent=d.toLocaleDateString("es-PR",{weekday:"long",day:"numeric",month:"long"}).replace(/^./,x=>x.toUpperCase())}clock();setInterval(clock,1000);show("login");